name: bin
version: '1.0'
maintainer: Dan Fithian
license: BSD3

default-extensions:
  - Arrows
  - ConstraintKinds
  - DataKinds
  - DeriveDataTypeable
  - DeriveGeneric
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - PackageImports
  - PatternSynonyms
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

ghc-options:
  - -Wall
  - -Werror
  - -fwarn-tabs
  - -threaded
  - -O2
  - -rtsopts
  - -with-rtsopts=-N
  - -with-rtsopts=-T

executables:
  create-user:
    main: create-user.hs
    source-dirs: .
    dependencies:
      - bytestring
      - classy-prelude
      - composite-base
      - cryptonite
      - dash-s3-feed
      - opaleye
      - optparse-applicative
      - postgresql-simple
