resolver: lts-8.23
packages:
- dash-s3-feed
- bin
extra-deps:
  - composite-aeson-0.4.2.0
  - composite-base-0.4.2.0
  - composite-opaleye-0.4.2.0
  - servant-multipart-0.10.0.1
  - servant-0.11
  - servant-server-0.11
flags: {}
extra-package-dbs: []
